
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/redux/provider";
import {IntlProvider,IntlConfig } from 'next-intl';
const inter = Inter({ subsets: ["latin"] });
import en from '../../messages/en.json';
import {NextIntlClientProvider, useMessages} from 'next-intl';


interface ExtendedIntlConfig extends IntlConfig {
  metadata?: Metadata;
}

export const metadata: Metadata = {
  title: "VoyageStack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string }; 
}) {
  return (
    <html lang={params.locale}>
      <body className={inter.className}>
        <main> <meta name="viewport" content="initial-scale=1, width=device-width" />
        <NextIntlClientProvider locale={params.locale} messages={en}>
        <ReduxProvider>
        <p></p>
              {children}
            
    </ReduxProvider>
     </NextIntlClientProvider>
       </main>
      </body>
    </html>
  );
}
